{"name": "test_two", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <py_test.test_py_02.TestClass object at 0x00000000038B5668>\n\n    @pytest.mark.xfail()\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_py_02.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "1911b7d5-f425-4062-a283-499de2dd0268-attachment.txt", "type": "text/plain"}], "start": 1639445438993, "stop": 1639445438993, "uuid": "6a2e387a-9da0-40d8-84de-d7c0d47f614b", "historyId": "6c2bcb20a9b0e140b3abc73842ff2e26", "testCaseId": "0cea8fd259d4f8cc5db77e71bab7acb9", "fullName": "test_py_02.TestClass#test_two", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_py_02"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "FXDN-20170826XB"}, {"name": "thread", "value": "9876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_py_02"}]}