{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <py_test.test_py_01.TestClass object at 0x00000000038851D0>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_py_01.py:28: AssertionError"}, "start": 1639445438932, "stop": 1639445438933, "uuid": "f9bfb226-2d0f-4c85-b588-a19ee45c42ca", "historyId": "527fe9044980a6cd671738291ae749dc", "testCaseId": "b47593c577501d0ea65efab98caedaec", "fullName": "test_py_01.TestClass#test_two", "labels": [{"name": "suite", "value": "test_py_01"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "FXDN-20170826XB"}, {"name": "thread", "value": "9876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_py_01"}]}