{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <py_test.test_py_01.TestClass object at 0x000000000383F358>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_py_01.py:28: AssertionError"}, "start": 1639445032459, "stop": 1639445032459, "uuid": "c7d9ffc2-6418-4e11-ac35-e1c118b87c3c", "historyId": "527fe9044980a6cd671738291ae749dc", "testCaseId": "b47593c577501d0ea65efab98caedaec", "fullName": "test_py_01.TestClass#test_two", "labels": [{"name": "suite", "value": "test_py_01"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "FXDN-20170826XB"}, {"name": "thread", "value": "8440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_py_01"}]}